### ISSUE TITLE
Schema file cannot be picked up from an excluded folder

### ISSUE THREAD

**Issue by jonnybbb** [jimkyndemeyer/js-graphql-intellij-plugin#334]
## Version and Environment Details
__Operation system__: MacOSX

__IDE name and version__: Intellij 2020.1.1

__Plugin version__: 2.4.0

## Expected Behaviour
The schemaPath can point to a file in an excluded Idea folder.  This used to work with Intellij 2019.x versions. 

## Actual Behaviour
If the schemaPath is pointing to a file in an excluded folder it is not found and therfor no graphql  code completion or validation is available. 

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
1. open a project with Intellij 2020.1.1
2. create a `.graphqlconfig` file with a schemaPath pointing to an excluded build directory from Idea. 

`.graphqlconfig`
```json
{
  "schemaPath": "build/generated/graphql/schema.json",
}
```
3. The GraphQL window will show the errors

**Comment by vepanimas** [comment]
To support this, we will need to change a significant part of the code 😞. This is why it won't be fixed in 2.6.0, but we will definitely support it in future releases.

**Comment by reckter** [comment]
I just had this happening to me as well, workaround is just not marking the folder as excluded ^^

**Comment by ingohachelbusch** [comment]
This problem still exists in version 2024.3 and with .env variables, even then they are not used in the graphql config file.
