### ISSUE TITLE
Failed to recognize directives input types

### ISSUE THREAD

**Issue by Hideman85** [jimkyndemeyer/js-graphql-intellij-plugin#388]
![image](https://user-images.githubusercontent.com/16165119/92922648-736a9e80-f436-11ea-8751-4c2332c9de34.png)

`schema.gql`
```gql
type User
@model(mutations: { create: "createUser", update: "updateUser" })
@auth(rules: [{
  allow: owner,
  provider: userPools,
  ownerField: "id",
  identityClaim: "sub",
  operations: [update]
}])
{
  id: ID! @Check(values: ["$ctx.identity.sub"])
  firstName: String!
  lastName: String!
  avatar: File
  address: Address # @FilterOut(cond: { op: NOT_EQUAL, values: ["$ctx.identity.sub"] })
  phoneNumber: String # @FilterOut(cond: { op: NOT_EQUAL, values: ["$ctx.identity.sub"] })
  currentOrganisationID: ID # @ReadOnly # set by a lambda
}
```

`awsDirectives.graphql`
```gql
scalar AWSDate
scalar AWSTime
scalar AWSDateTime
scalar AWSTimestamp
scalar AWSEmail
scalar AWSJSON
scalar AWSURL
scalar AWSPhone
scalar AWSIPAddress

##########################################################
##          Model
##########################################################
directive @model(
  queries: ModelQueryMap
  mutations: ModelMutationMap
  subscriptions: ModelSubscriptionMap
  timestamps: TimestampConfiguration
) on OBJECT
input ModelMutationMap {
  create: String
  update: String
  delete: String
}
input ModelQueryMap {
  get: String
  list: String
}
input ModelSubscriptionMap {
  onCreate: [String]
  onUpdate: [String]
  onDelete: [String]
  level: ModelSubscriptionLevel
}
enum ModelSubscriptionLevel {
  off
  public
  on
}
input TimestampConfiguration {
  createdAt: String
  updatedAt: String
}

##########################################################
##          Auth
##########################################################
directive @auth(rules: [AuthRule!]!) on OBJECT | FIELD_DEFINITION
input AuthRule {
  allow: AuthStrategy!
  provider: AuthProvider
  ownerField: String # defaults to "owner" when using owner auth
  identityClaim: String # defaults to "username" when using owner auth
  groupClaim: String # defaults to "cognito:groups" when using Group auth
  groups: [String]  # Required when using Static Group auth
  groupsField: String # defaults to "groups" when using Dynamic Group auth
  operations: [ModelOperation] # Required for finer control

  # The following arguments are deprecated. It is encouraged to use the 'operations' argument.
  queries: [ModelQuery]
  mutations: [ModelMutation]
}
enum AuthStrategy { owner groups private public }
enum AuthProvider { apiKey iam oidc userPools }
enum ModelOperation { create update delete read }

# The following objects are deprecated. It is encouraged to use ModelOperations.
enum ModelQuery { get list }
enum ModelMutation { create update delete }

##########################################################
##          Key
##########################################################
directive @key(fields: [String!]!, name: String, queryField: String) on OBJECT

##########################################################
##          Connextion
##########################################################
directive @connection(keyName: String, fields: [String!]) on FIELD_DEFINITION

##########################################################
##          Function / Lambda
##########################################################
directive @function(name: String!, region: String) on FIELD_DEFINITION

##########################################################
##          Searchable / Elasticsearch
##########################################################
# Streams data from DynamoDB to Elasticsearch and exposes search capabilities.
directive @searchable(queries: SearchableQueryMap) on OBJECT
input SearchableQueryMap { search: String }

##########################################################
##          HTTP / Slack for ex
##########################################################
directive @http(method: HttpMethod, url: String!, headers: [HttpHeader]) on FIELD_DEFINITION
enum HttpMethod { PUT POST GET DELETE PATCH }
input HttpHeader {
  key: String
  value: String
}
```

The directives file is correctly included in `.graphqlconfig` and the directives don't have any issues. The issues come on the arguments of these directives and it looks like the plugin failed to find the input types. Can be related to https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/348

I'am using the latest WebStorm with the latest plugin version (2.6.0)

**Comment by vepanimas** [comment]
@Hideman85 hello, thank you for this report, I'll check it out.

**Comment by vepanimas** [comment]
@Hideman85 unfortunately, it turns out that resolving/completion object directive arguments is not supported at all at the moment. I checked it in the 2.4.0 version to be sure it is not a regression. So, it will take some time to implement it, I think the fix will be available in the next release.

**Comment by dsypniewski** [comment]
I was having the same problem and in my testing it seems that as soon as any of the defined directives are invalid on the first level of input nested data types are not checked and marked as invalid, as soon as I've fixed the directive that was causing this the nested data types are checked.

@Hideman85 I see that you are using Amplify as am I, the problem in my case was the `@connection` directive which seem to be different in documentation and source code and should be instead:
```
directive @connection(
  name: String
  keyField: String
  sortField: String
  keyName: String
  limit: Int
  fields: [String!]
) on FIELD_DEFINITION
```

**Comment by dhyeyshah** [comment]
Any updates on this front? This is still happening in the @auth directive of amplify. Even when we use this defination 
`
directive @auth(
  rules: [AuthRule!]!
) on OBJECT

input AuthRule {
  allow: AuthStrategy!
  ownerField: String
  groups: [String]
  operations: [ModelOperation]
}

enum AuthStrategy { owner groups private public }

enum ModelOperation { create update delete read }
`

It will not recognise allow field within rules. When can we expect this to be fixed?

**Comment by noorulh06** [comment]
WebStorm is not able to recognise graphQL @client and @export directive.

**Comment by vepanimas** [comment]
Should be fixed in 3.0.0.

@noorulh06 Please, look at this comment https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/490#issuecomment-913064903.
